#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Color {
    Transparent = 0,
    DarkPlum,
    DeepSlate,
    DustyPurple,
    MutedMauve,
    WarmKhaki,
    PlumGray,
    LavenderGray,
    BlueGray,
    PaleMint,
    White,
    DarkRed,
    BrickRed,
    Vermilion,
    Coral,
    Crimson,
    BrightRed,
    Orange,
    Amber,
    GoldenYellow,
    Wine,
    Rust,
    BurntOrange,
    Apricot,
    Sand,
    DarkOlive,
    Olive,
    LimeOlive,
    YellowGreen,
    PaleYellow,
    DarkTeal,
    Teal,
    Green,
    Lime,
    PaleLime,
    Charcoal,
    ForestGray,
    Sage,
    PaleSage,
    Seaweed,
    DeepCyan,
    Cyan,
    Turquoise,
    Aqua,
    PaleAqua,
    Navy,
    SlateBlue,
    RoyalBlue,
    Azure,
    SkyBlue,
    DarkPurple,
    Purple,
    Violet,
    Lavender,
    PaleLavender,
    Mulberry,
    Berry,
    Rose,
    Pink,
    DarkMagenta,
    Magenta,
    HotPink,
    Salmon,
    Peach,
    Blush,
}

impl Color {
    pub const ALL: [Self; 64] = [
        Self::DarkPlum,
        Self::DeepSlate,
        Self::DustyPurple,
        Self::MutedMauve,
        Self::WarmKhaki,
        Self::PlumGray,
        Self::LavenderGray,
        Self::BlueGray,
        Self::PaleMint,
        Self::White,
        Self::DarkRed,
        Self::BrickRed,
        Self::Vermilion,
        Self::Coral,
        Self::Crimson,
        Self::BrightRed,
        Self::Orange,
        Self::Amber,
        Self::GoldenYellow,
        Self::Wine,
        Self::Rust,
        Self::BurntOrange,
        Self::Apricot,
        Self::Sand,
        Self::DarkOlive,
        Self::Olive,
        Self::LimeOlive,
        Self::YellowGreen,
        Self::PaleYellow,
        Self::DarkTeal,
        Self::Teal,
        Self::Green,
        Self::Lime,
        Self::PaleLime,
        Self::Charcoal,
        Self::ForestGray,
        Self::Sage,
        Self::PaleSage,
        Self::Seaweed,
        Self::DeepCyan,
        Self::Cyan,
        Self::Turquoise,
        Self::Aqua,
        Self::PaleAqua,
        Self::Navy,
        Self::SlateBlue,
        Self::RoyalBlue,
        Self::Azure,
        Self::SkyBlue,
        Self::DarkPurple,
        Self::Purple,
        Self::Violet,
        Self::Lavender,
        Self::PaleLavender,
        Self::Mulberry,
        Self::Berry,
        Self::Rose,
        Self::Pink,
        Self::DarkMagenta,
        Self::Magenta,
        Self::HotPink,
        Self::Salmon,
        Self::Peach,
        Self::Blush,
    ];

    pub const fn rgb(self) -> [u8; 3] {
        match self {
            Self::Transparent => [0, 0, 0],
            Self::DarkPlum => [0x2e, 0x22, 0x2f],
            Self::DeepSlate => [0x3e, 0x35, 0x46],
            Self::DustyPurple => [0x62, 0x55, 0x65],
            Self::MutedMauve => [0x96, 0x6c, 0x6c],
            Self::WarmKhaki => [0xab, 0x94, 0x7a],
            Self::PlumGray => [0x69, 0x4f, 0x62],
            Self::LavenderGray => [0x7f, 0x70, 0x8a],
            Self::BlueGray => [0x9b, 0xab, 0xb2],
            Self::PaleMint => [0xc7, 0xdc, 0xd0],
            Self::White => [0xff, 0xff, 0xff],
            Self::DarkRed => [0x6e, 0x27, 0x27],
            Self::BrickRed => [0xb3, 0x38, 0x31],
            Self::Vermilion => [0xea, 0x4f, 0x36],
            Self::Coral => [0xf5, 0x7d, 0x4a],
            Self::Crimson => [0xae, 0x23, 0x34],
            Self::BrightRed => [0xe8, 0x3b, 0x3b],
            Self::Orange => [0xfb, 0x6b, 0x1d],
            Self::Amber => [0xf7, 0x96, 0x17],
            Self::GoldenYellow => [0xf9, 0xc2, 0x2b],
            Self::Wine => [0x7a, 0x30, 0x45],
            Self::Rust => [0x9e, 0x45, 0x39],
            Self::BurntOrange => [0xcd, 0x68, 0x3d],
            Self::Apricot => [0xe6, 0x90, 0x4e],
            Self::Sand => [0xfb, 0xb9, 0x54],
            Self::DarkOlive => [0x4c, 0x3e, 0x24],
            Self::Olive => [0x67, 0x66, 0x33],
            Self::LimeOlive => [0xa2, 0xa9, 0x47],
            Self::YellowGreen => [0xd5, 0xe0, 0x4b],
            Self::PaleYellow => [0xfb, 0xff, 0x86],
            Self::DarkTeal => [0x16, 0x5a, 0x4c],
            Self::Teal => [0x23, 0x90, 0x63],
            Self::Green => [0x1e, 0xbc, 0x73],
            Self::Lime => [0x91, 0xdb, 0x69],
            Self::PaleLime => [0xcd, 0xdf, 0x6c],
            Self::Charcoal => [0x31, 0x36, 0x38],
            Self::ForestGray => [0x37, 0x4e, 0x4a],
            Self::Sage => [0x54, 0x7e, 0x64],
            Self::PaleSage => [0x92, 0xa9, 0x84],
            Self::Seaweed => [0xb2, 0xba, 0x90],
            Self::DeepCyan => [0x0b, 0x5e, 0x65],
            Self::Cyan => [0x0b, 0x8a, 0x8f],
            Self::Turquoise => [0x0e, 0xaf, 0x9b],
            Self::Aqua => [0x30, 0xe1, 0xb9],
            Self::PaleAqua => [0x8f, 0xf8, 0xe2],
            Self::Navy => [0x32, 0x33, 0x53],
            Self::SlateBlue => [0x48, 0x4a, 0x77],
            Self::RoyalBlue => [0x4d, 0x65, 0xb4],
            Self::Azure => [0x4d, 0x9b, 0xe6],
            Self::SkyBlue => [0x8f, 0xd3, 0xff],
            Self::DarkPurple => [0x45, 0x29, 0x3f],
            Self::Purple => [0x6b, 0x3e, 0x75],
            Self::Violet => [0x90, 0x5e, 0xa9],
            Self::Lavender => [0xa8, 0x84, 0xf3],
            Self::PaleLavender => [0xea, 0xad, 0xed],
            Self::Mulberry => [0x75, 0x3c, 0x54],
            Self::Berry => [0xa2, 0x4b, 0x6f],
            Self::Rose => [0xcf, 0x65, 0x7f],
            Self::Pink => [0xed, 0x80, 0x99],
            Self::DarkMagenta => [0x83, 0x1c, 0x5d],
            Self::Magenta => [0xc3, 0x24, 0x54],
            Self::HotPink => [0xf0, 0x4f, 0x78],
            Self::Salmon => [0xf6, 0x81, 0x81],
            Self::Peach => [0xfc, 0xa7, 0x90],
            Self::Blush => [0xfd, 0xcb, 0xb0],
        }
    }
}
