[package]
name = "api"
version = "0.1.0"
edition = "2024"

[features]
default = []
dev = []

[dependencies]
utils.git = "https://codeberg.org/avitrano/utils"
# for asset hashing
blake3 = "1.8"
glam = "0.34"
glow = "0.18"
serde = "1.0"
sdl3 = "0.20"
thiserror = "2.0"
toml = "1.1"
uuid = { version = "1.27", features = ["v4"] }
